### ISSUE TITLE
Should throw Exception if value is not valid

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-WuttipatNilsiri#11]
For example if someone try to `createMoney` with value `43` on `ThaiMoneyFactory`, it should throw Exception because it is not a valid money.

From Lab Instruction:
> create new money object in the local currency. If the value is not a valid currency amount, then throw IllegalArgumentException. You must include a String message in the exception that describes the problem, e.g. "100,000 is not a valid currency value".

**Comment by WuttipatNilsiri** [comment]
> if (value < 0){
			throw new IllegalArgumentException("invalid input" + value);
		}
		else if (value >= 20){
			if(!isBankNote(value)){
				throw new IllegalArgumentException("invalid input" + value);
			}else
				countgen++;
				return new BankNote(value,CURRENCY,countgen);
		}
		else 
			if(!isCoin(value)){
				throw new IllegalArgumentException("invalid input" + value);
			}else
				return new Coin(value,CURRENCY);
fix with something like this

**Comment by WuttipatNilsiri** [comment]
change to 
`if(isBankNote(value)){
			countgen++;
			return new BankNote(value,CURRENCY,countgen);
		}
		else if(isCoin(value)){
			return new Coin(value,CURRENCY);
		}
		else 
			throw new IllegalArgumentException("invalid input" + value);`
