### ISSUE TITLE
Incorrect Exception handling

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-WuttipatNilsiri#12]
MoneyFactory `createMoney` should throw `IllegalArgumentException` not just printing them.

After catching, you should transform the exception into `IllegalArgumentException` with messages. By `throw new IllegalArgumentException("error message", e);`

**Comment by WuttipatNilsiri** [comment]
> if (value < 0){
			throw new IllegalArgumentException("invalid input" + value);
		}
		else if (value >= 20){
			if(!isBankNote(value)){
				throw new IllegalArgumentException("invalid input" + value);
			}else
				countgen++;
				return new BankNote(value,CURRENCY,countgen);
		}
		else 
			if(!isCoin(value)){
				throw new IllegalArgumentException("invalid input" + value);
			}else
				return new Coin(value,CURRENCY);

**Comment by WuttipatNilsiri** [comment]
fix with something like this

**Comment by kykungz** [comment]
https://github.com/OOP2018/coinpurse-WuttipatNilsiri/blob/fbaa34442ee146b3ba8eaff12594b4e128fe8715/src/coinpurse/MoneyFactory.java#L50-L52

**Comment by WuttipatNilsiri** [comment]
fix
