### ISSUE TITLE
A lot of typos in javadoc

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-WuttipatNilsiri#13]
Please be careful with the spellings, for example `defaul` should be `default` and your name's first character should be a capital letter.

**Comment by WuttipatNilsiri** [comment]
`if (value < 0){
			throw new IllegalArgumentException("invalid input" + value);
		}
		else if (value >= 20){
			if(!isBankNote(value)){
				throw new IllegalArgumentException("invalid input" + value);
			}else
				countgen++;
				return new BankNote(value,CURRENCY,countgen);
		}
		else 
			if(!isCoin(value)){
				throw new IllegalArgumentException("invalid input" + value);
			}else
				return new Coin(value,CURRENCY);`
fix with something like this

**Comment by WuttipatNilsiri** [comment]
edited
