### ISSUE TITLE
Every BankNote has same serialNumber

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-WuttipatNilsiri#3]
https://github.com/OOP2018/coinpurse-WuttipatNilsiri/blob/ca9475778e39cfd1f732c16cc2fb2778613c3086/src/coinpurse/Banknote.java#L16-L36

I saw you use Math.random() to create BankNote, however, there is a chance to random and get the same number.

**Comment by taveratch** [comment]
If BankNote's Constructor accepts serialNumber, have you considered factory class to creat BankNote and store SerialNumber is it.

**Comment by WuttipatNilsiri** [comment]
when Non serialNumber Constructor change to use math.ran to gen serialNumber

**Comment by taveratch** [comment]
Since you are using Math.random(), How do you guarantee that SerialNumber will unique?

**Comment by WuttipatNilsiri** [comment]
then i will have count times of generate
