### ISSUE TITLE
it seems like your money is not sorted

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-WuttipatNilsiri#5]
https://github.com/OOP2018/coinpurse-WuttipatNilsiri/blob/ca9475778e39cfd1f732c16cc2fb2778613c3086/src/coinpurse/Purse.java#L100

**Comment by WuttipatNilsiri** [comment]
https://imgur.com/a/SQFA5
i think already sorted ...

**Comment by taveratch** [comment]
Yes it is. Actually nothing wrong with your code but if I have another sub-class of Valuable (maybe `Coupon implements Valuable`). Do I need to write compareTo with the same logic again?

**Comment by WuttipatNilsiri** [comment]
i dont know without using abstract class then i will use it

**Comment by taveratch** [comment]
Actually, everything you want is explained in the instruction. 
Here is the thing, BankNote and Coin implement Valuable and they don't need to know how to compare each other. However, there are two things that both have in common are getValue() and getCurrency().

Since you know the common characteristics of BankNote and Coin, would it be better if you write a utility to do something you want? In this case would be `ValueComparator.java`.  which a tool for comparing between two `Valuable`s.

Think further, If I have Coupon.java implements Valuable. I don't need to write compareTo in Coupon again because I already have ValueComparator.java.

**Comment by WuttipatNilsiri** [comment]
i have add valuecomparator
