### ISSUE TITLE
SerialNumber should be started from 1000000 not 0

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-WuttipatNilsiri#6]
https://github.com/OOP2018/coinpurse-WuttipatNilsiri/blob/f9bc3d89eb3c8effbfe621f810a7f55cc698355f/src/coinpurse/Banknote.java#L36-L43

**Comment by WuttipatNilsiri** [comment]
i have fix to start with 10000000

**Comment by WuttipatNilsiri** [comment]
count at console dialog
