### ISSUE TITLE
Duplicate code!

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-WuttipatNilsiri#7]
https://github.com/OOP2018/coinpurse-WuttipatNilsiri/blob/6ed2fff31bfd3503801f50bdb8a40b5e78a08965/src/coinpurse/Purse.java#L135

https://github.com/OOP2018/coinpurse-WuttipatNilsiri/blob/6ed2fff31bfd3503801f50bdb8a40b5e78a08965/src/coinpurse/Purse.java#L152

Would it be better if you move these duplicate code to the big withdraw()?

**Comment by WuttipatNilsiri** [comment]
fix
